name: learning_high_res
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20210324.2
  - absl-py=0.15.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - alsa-lib=1.2.7.2
  - aom=3.3.0
  - asttokens=2.0.8
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=22.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blinker=1.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.6.15.1
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=4.2.4
  - certifi=2022.6.15.1
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - colorama=0.4.5
  - cryptography=37.0.4
  - cudatoolkit=11.7.0
  - cudnn=8.4.1.50
  - cycler=0.11.0
  - dbus=1.13.6
  - debugpy=1.6.3
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=1.0.0
  - expat=2.4.8
  - ffmpeg=5.0.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.37.1
  - freetype=2.12.1
  - frozenlist=1.3.1
  - gast=0.4.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.72.1
  - glib-tools=2.72.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - google-auth=1.35.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpc-cpp=1.41.1
  - grpcio=1.41.1
  - gst-plugins-base=1.20.3
  - gstreamer=1.20.3
  - h5py=3.1.0
  - hdf5=1.10.6
  - icu=69.1
  - idna=3.3
  - importlib-metadata=4.11.4
  - ipykernel=6.14.0
  - ipython=8.4.0
  - jedi=0.18.1
  - joblib=1.1.0
  - jpeg=9e
  - jupyter_client=7.3.5
  - jupyter_core=4.11.1
  - keras=2.6.0
  - keras-preprocessing=1.1.2
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=13.0.1
  - libcurl=7.83.1
  - libdeflate=1.14
  - libdrm=2.4.113
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=12.1.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libglib=2.72.1
  - libgomp=12.1.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libllvm13=13.0.1
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpciaccess=0.16
  - libpng=1.6.37
  - libpq=14.5
  - libprotobuf=3.18.1
  - libsodium=1.0.18
  - libsqlite=3.39.3
  - libssh2=1.10.0
  - libstdcxx-ng=12.1.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libva=2.15.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzlib=1.2.12
  - llvmlite=0.38.1
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.6
  - mpc=1.2.1
  - mpfr=4.1.0
  - mpmath=1.2.1
  - multidict=6.0.2
  - munkres=1.1.4
  - mysql-common=8.0.30
  - mysql-libs=8.0.30
  - nccl=2.14.3.1
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nettle=3.6
  - nspr=4.32
  - nss=3.78
  - numba=0.55.2
  - numpy=1.19.5
  - oauthlib=3.2.1
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=1.1.1q
  - opt_einsum=3.3.0
  - packaging=21.3
  - pandas=1.4.4
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - prompt-toolkit=3.0.31
  - protobuf=3.18.1
  - psutil=5.9.2
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-pde=0.21.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pygments=2.13.0
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.12.3
  - pysocks=1.7.1
  - python=3.9.13
  - python-dateutil=2.8.2
  - python-flatbuffers=1.12
  - python_abi=3.9
  - pytz=2022.2.1
  - pyu2f=0.1.5
  - pyzmq=23.2.1
  - qt=5.12.9
  - re2=2021.11.01
  - readline=8.1.2
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - scikit-learn=1.1.2
  - scipy=1.9.1
  - setuptools=65.3.0
  - six=1.15.0
  - snappy=1.1.9
  - sqlite=3.39.3
  - stack_data=0.5.0
  - svt-av1=0.9.1
  - sympy=1.10.1
  - tensorboard=2.6.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.6.2
  - tensorflow-base=2.6.2
  - tensorflow-estimator=2.6.2
  - tensorflow-gpu=2.6.2
  - termcolor=1.1.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.4.0
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - tzdata=2022c
  - unicodedata2=14.0.0
  - urllib3=1.26.11
  - wcwidth=0.2.5
  - werkzeug=2.2.2
  - wheel=0.37.1
  - wrapt=1.12.1
  - x264=1!161.3030
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yarl=1.7.2
  - zeromq=4.3.4
  - zipp=3.8.1
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1

